title: "Jane Doe — Cybersecurity Portfolio"
description: "A growing portfolio of cybersecurity projects and coursework."
name: "Jane Doe"
bio: "Cybersecurity student focused on incident response and malware analysis."
avatar_url: "https://avatars.githubusercontent.com/u/000000?v=4"
portfolio_url: "https://github.com/Hocking-College-Cybersecurity/student-portfolio"